In [174]:
import numpy as np
from sympy import symbols, Matrix, simplify
import matplotlib.pyplot as plt
from pyscf import gto, scf
from scipy.linalg import fractional_matrix_power
import sys
sys.path.append('/workspaces/bachelor-project-bridging-profile-Mattice-Criel/projects/Project-MatticeCriel/Benzene/rhf')
import plottingsystem as pts
import sys
sys.path.append('/workspaces/bachelor-project-bridging-profile-Mattice-Criel/projects/Project-MatticeCriel/Benzene/Huckel')
from class_huckel import huckel

In [175]:
benzene_molecule = '''
  C    1.2116068    0.6995215    0.0000000
  C    1.2116068   -0.6995215    0.0000000
  C   -0.0000000   -1.3990430   -0.0000000
  C   -1.2116068   -0.6995215   -0.0000000
  C   -1.2116068    0.6995215   -0.0000000
  C    0.0000000    1.3990430    0.0000000
  H    2.1489398    1.2406910    0.0000000
  H    2.1489398   -1.2406910    0.0000000
  H   -0.0000000   -2.4813820   -0.0000000
  H   -2.1489398   -1.2406910   -0.0000000
  H   -2.1489398    1.2406910   -0.0000000
  H    0.0000000    2.4813820    0.0000000
'''
extra_bounds = [(0,5)]
coordinates = pts.taking_x_and_y_coordinate(pts.taking_carbon_coordinates(benzene_molecule))
print(coordinates)


[[ 1.2116068  0.6995215]
 [ 1.2116068 -0.6995215]
 [-0.        -1.399043 ]
 [-1.2116068 -0.6995215]
 [-1.2116068  0.6995215]
 [ 0.         1.399043 ]]


In [176]:
benzene = huckel(6, 0, -3)
benzene.create_matrix()
benzene.huckel_matrix[0][0] = -0
H = benzene.huckel_matrix
print(H)

[[ 0. -3.  0.  0.  0. -3.]
 [-3.  0. -3.  0.  0.  0.]
 [ 0. -3.  0. -3.  0.  0.]
 [ 0.  0. -3.  0. -3.  0.]
 [ 0.  0.  0. -3.  0. -3.]
 [-3.  0.  0.  0. -3.  0.]]


In [177]:
benzene.solve_huckel_matrix()
eigenvectors = benzene.eigenvectors.T
eigenvalues = benzene.eigenvalues
print(eigenvalues)
print(eigenvectors[:3])

[-6. -3. -3.  3.  3.  6.]
[[ 4.08248097e-01  4.08248097e-01  4.08248097e-01  4.08248097e-01
   4.08248097e-01  4.08248097e-01]
 [-5.77350406e-01 -2.88675203e-01  2.88675203e-01  5.77350406e-01
   2.88675203e-01 -2.88675203e-01]
 [ 0.00000000e+00 -5.00000119e-01 -5.00000119e-01 -4.35210020e-18
   5.00000119e-01  5.00000119e-01]]


In [178]:
mat = np.zeros((6,6))
mat[0][0] = 1
print(mat)
print(eigenvectors[:3])
density = eigenvectors[:3] @mat@ eigenvectors[:3].T
print(density.round(6))


[[1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[ 4.08248097e-01  4.08248097e-01  4.08248097e-01  4.08248097e-01
   4.08248097e-01  4.08248097e-01]
 [-5.77350406e-01 -2.88675203e-01  2.88675203e-01  5.77350406e-01
   2.88675203e-01 -2.88675203e-01]
 [ 0.00000000e+00 -5.00000119e-01 -5.00000119e-01 -4.35210020e-18
   5.00000119e-01  5.00000119e-01]]
[[ 0.166667 -0.235702  0.      ]
 [-0.235702  0.333333  0.      ]
 [ 0.        0.        0.      ]]


In [179]:
eigval, eigvec = np.linalg.eigh(density)
print(eigval, eigvec)


[0.  0.  0.5] [[-0.81649677  0.         -0.57735   ]
 [-0.57735     0.          0.81649677]
 [-0.          1.          0.        ]]


In [180]:
S_ohm = 0
for eigenvalue in eigval:
    if (eigenvalue != 0):
        S_ohm -= (eigenvalue*np.log(eigenvalue) + (1-eigenvalue)*np.log(1-eigenvalue))
print(2*S_ohm)

print(np.log(2))

1.3862943611198906
0.6931471805599453


In [181]:
mat1 = np.zeros((6,6))
mat2 = np.zeros((6,6))
mat1[0][0] = 1
mat2[1][1]= 1

mat1_2 = mat1 + mat2
print(mat1_2)
print(eigenvectors[:3])
eigenvectors[:3] @mat1@ eigenvectors[:3].T

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[ 4.08248097e-01  4.08248097e-01  4.08248097e-01  4.08248097e-01
   4.08248097e-01  4.08248097e-01]
 [-5.77350406e-01 -2.88675203e-01  2.88675203e-01  5.77350406e-01
   2.88675203e-01 -2.88675203e-01]
 [ 0.00000000e+00 -5.00000119e-01 -5.00000119e-01 -4.35210020e-18
   5.00000119e-01  5.00000119e-01]]


array([[ 0.16666651, -0.2357022 ,  0.        ],
       [-0.2357022 ,  0.33333349,  0.        ],
       [ 0.        ,  0.        ,  0.        ]])

In [182]:
occ_orbitals = eigenvectors[:3]
S_ohm_1_atom= []
S_ohm_2_atoms = []
for i in range(6):
    atom_i = np.zeros((6,6))
    atom_i[i][i] = 1
    eigvals_i = np.linalg.eigvalsh(occ_orbitals @ atom_i @ occ_orbitals.T).round(6)
    S_ohm_i = 0
    for eigenvalue in eigvals_i:
        if (eigenvalue != 0): 
            S_ohm_i -= (eigenvalue*np.log(eigenvalue) + (1-eigenvalue)*np.log(1-eigenvalue))
    S_ohm_1_atom.append(2*S_ohm_i)
    for j in range(i+1,6):
        atom_j = np.zeros((6,6))
        atom_j[j][j] = 1    
        atom_i_j = atom_i + atom_j
        eigvals_i_j = np.linalg.eigvalsh(occ_orbitals @ atom_i_j @ occ_orbitals.T).round(6)
        S_ohm_i_j = 0
        for eigenvalue in eigvals_i_j:
            if (eigenvalue != 0): 
                S_ohm_i_j -= (eigenvalue*np.log(eigenvalue) + (1-eigenvalue)*np.log(1-eigenvalue))
        S_ohm_2_atoms.append(2*S_ohm_i_j)
print(S_ohm_1_atom)
print(S_ohm_2_atoms)
I_1_2 = S_ohm_1_atom[0] + S_ohm_1_atom[1] - S_ohm_2_atoms[0]
print(I_1_2)
I_1_3 = S_ohm_1_atom[0] + S_ohm_1_atom[2] - S_ohm_2_atoms[1]
print(I_1_3)
I_1_4 = S_ohm_1_atom[0] + S_ohm_1_atom[3] - S_ohm_2_atoms[2]
print(I_1_4)
I_1_5 = S_ohm_1_atom[0] + S_ohm_1_atom[4] - S_ohm_2_atoms[3]
print(I_1_5)
I_1_6 = S_ohm_1_atom[0] + S_ohm_1_atom[5] - S_ohm_2_atoms[4]
print(I_1_6)
# Dit ziet er goed uit volgens mij. 
I_5_3 = S_ohm_1_atom[4] + S_ohm_1_atom[2] - S_ohm_2_atoms[5+4+2-1]
print(I_5_3)

[1.3862943611198906, 1.3862943611198906, 1.3862943611198906, 1.3862943611198906, 1.3862943611198906, 1.3862943611198906]
[1.8022469813808355, 2.772588722239781, 2.5460557489820106, 2.772588722239781, 1.8022469813808355, 1.8022469813808355, 2.772588722239781, 2.5460557489820106, 2.772588722239781, 1.8022469813808355, 2.772588722239781, 2.5460557489820106, 1.8022469813808355, 2.772588722239781, 1.8022469813808355]
0.9703417408589456
0.0
0.22653297325777055
0.0
0.9703417408589456
0.0
