In this notebook i will calculate the molecular orbitals of pentadiene. This to show why we can expect the correlation patterns we see in benzene. We also calculate the entangelment patterns. 

In [8]:
import numpy as np
from sympy import symbols, Matrix, simplify
import matplotlib.pyplot as plt
from pyscf import gto, scf
from scipy.linalg import fractional_matrix_power
import sys
sys.path.append('/workspaces/Huckel-on-benzene/project/Benzene/rhf')
import plottingsystem as pts
import sys
sys.path.append('/workspaces/Huckel-on-benzene/project/Benzene/Huckel')
from class_huckel import huckel

In [9]:
benzene_molecule = '''
  C    1.2116068    0.6995215    0.0000000
  C    1.2116068   -0.6995215    0.0000000
  C   -0.0000000   -1.3990430   -0.0000000
  C   -1.2116068   -0.6995215   -0.0000000
  C   -1.2116068    0.6995215   -0.0000000
  C    0.0000000    1.3990430    0.0000000
  H    2.1489398    1.2406910    0.0000000
  H    2.1489398   -1.2406910    0.0000000
  H   -0.0000000   -2.4813820   -0.0000000
  H   -2.1489398   -1.2406910   -0.0000000
  H   -2.1489398    1.2406910   -0.0000000
  H    0.0000000    2.4813820    0.0000000
'''
extra_bounds = [(0,5)]
coordinates = pts.taking_x_and_y_coordinate(pts.taking_carbon_coordinates(benzene_molecule))
print(coordinates)


[[ 1.2116068  0.6995215]
 [ 1.2116068 -0.6995215]
 [-0.        -1.399043 ]
 [-1.2116068 -0.6995215]
 [-1.2116068  0.6995215]
 [ 0.         1.399043 ]]


In [10]:
pentabutadiene = huckel(5, 0, -3)
pentabutadiene.create_matrix()
H = pentabutadiene.huckel_matrix
H[0,4] = 0
H[4,0] = 0
print(H)

[[ 0. -3.  0.  0.  0.]
 [-3.  0. -3.  0.  0.]
 [ 0. -3.  0. -3.  0.]
 [ 0.  0. -3.  0. -3.]
 [ 0.  0.  0. -3.  0.]]


In [15]:
pentabutadiene.solve_huckel_matrix()
eigenvectors = pentabutadiene.eigenvectors.T
eigenvalues = pentabutadiene.eigenvalues

print(eigenvalues)
print(eigenvectors.round(6))

[-5.196152 -3.       -0.        3.        5.196152]
[[ 0.288675  0.5       0.57735   0.5       0.288675]
 [-0.5      -0.5      -0.        0.5       0.5     ]
 [-0.57735  -0.        0.57735  -0.       -0.57735 ]
 [-0.5       0.5      -0.       -0.5       0.5     ]
 [ 0.288675 -0.5       0.57735  -0.5       0.288675]]
