In [28]:
import numpy as np
import sys
sys.path.append('/workspaces/bachelor-project-bridging-profile-Mattice-Criel/projects/Project-MatticeCriel/Benzene/Huckel')
from class_huckel import huckel
Benzene = huckel(6, -0, -0.5)
Benzene.create_matrix()

huc_mat = Benzene.huckel_matrix
print(huc_mat)

[[ 0.  -0.5  0.   0.   0.  -0.5]
 [-0.5  0.  -0.5  0.   0.   0. ]
 [ 0.  -0.5  0.  -0.5  0.   0. ]
 [ 0.   0.  -0.5  0.  -0.5  0. ]
 [ 0.   0.   0.  -0.5  0.  -0.5]
 [-0.5  0.   0.   0.  -0.5  0. ]]


In [29]:
sigma_h = huckel(6, -1, 0, 'lin')
sigma_h.create_matrix()

sigma_h_matrix = sigma_h.huckel_matrix
print(sigma_h_matrix)

[[-1.  0.  0.  0.  0.  0.]
 [ 0. -1.  0.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.  0.]
 [ 0.  0.  0. -1.  0.  0.]
 [ 0.  0.  0.  0. -1.  0.]
 [ 0.  0.  0.  0.  0. -1.]]


In [30]:
vector = np.array([2,1,1,1,1,1])

print(vector)

[2 1 1 1 1 1]


In [31]:
print((huc_mat @ sigma_h_matrix @ vector) - (sigma_h_matrix @ huc_mat @ vector))

[0. 0. 0. 0. 0. 0.]
