In [12]:
import numpy as np
from sympy import symbols, Matrix, simplify, pprint
import matplotlib.pyplot as plt
from pyscf import gto, scf
import sys
sys.path.append('/workspaces/bachelor-project-bridging-profile-Mattice-Criel/projects/Project-MatticeCriel/Benzene/rhf')

import plottingsystem as pts
molecule = """
  C    0.0000000    0.5332410   -1.4948079
  C    0.0000000   -0.5772294   -0.7487961
  C    0.0000000   -0.5544554    0.7292193
  N    0.0000000    0.5501390    1.3840783
  H    0.0000000    0.4565477   -2.5773265
  H    0.0000000    1.5210246   -1.0445631
  H    0.0000000   -1.5419479   -1.2467417
  H    0.0000000   -1.4983417    1.2666090
  H    0.0000000    0.5490508    2.4143034
"""

# Converteer de coördinaten naar een NumPy-array
carbon_coordinates = pts.taking_carbon_coordinates(molecule)
coordinates = pts.taking_x_and_y_coordinate(carbon_coordinates)
print(coordinates)

[[-1.4948079  0.533241 ]
 [-0.7487961 -0.5772294]
 [ 0.7292193 -0.5544554]
 [ 1.3840783  0.550139 ]]


In [13]:
_molecule = gto.M(atom=molecule, basis='sto-3g')#'sto-6g''ccpvdz'

pz_indices = pts.taking_indices(_molecule, ['C 2px', 'N 2px'])
print(pz_indices)
hf = scf.RHF(_molecule)
hf_energy = hf.kernel()

[2, 7, 12, 17]
converged SCF energy = -168.761735735589


In [14]:
mo_coeff = hf.mo_coeff.round(6)
mo_coeff = pts.normaliseer(mo_coeff)

In [15]:
mo_eigenvalues = hf.mo_energy[[12,14, 15, 16]]
pz_orbitals = mo_coeff[pz_indices][:,[12,14, 15, 16]]
print(pz_orbitals)


[[ 0.31447177  0.59890343  0.5686637  -0.43734678]
 [ 0.45721478  0.53649581 -0.38772132  0.58703437]
 [ 0.62812517 -0.31582132 -0.45889111 -0.55579143]
 [ 0.54545479 -0.50372991  0.5618832   0.3939725 ]]


In [16]:
D = pts.making_D(pz_orbitals, 4)
print(np.diag(D))


[0.91515564 0.99374621 0.98856866 1.10252949]


1. [0.95906023 0.95984406 0.97545552 0.91566985 0.9777383  1.21223204]
2. [0.91859922 0.92992355 0.88367969 1.0411525  2.22664503]
3. [0.95152746 0.97562361 0.90287582 0.98859228 0.97030993 1.21107089]
4. [0.97713185 0.92624311 1.00932689 0.89769242 2.18960573]
5. [0.94751994 1.00490172 1.06052844 0.9870499 ]
6. [0.91515564 0.99374621 0.98856866 1.10252949]
